# Generated by Django 3.0.11 on 2020-12-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ap',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='user',
            name='at',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='user',
            name='ep',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='rh',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='user',
            name='v',
            field=models.FloatField(default=50.0),
        ),
    ]
